const router=require('express').Router()
const {login,register,getAllUserProfile,deleteUser,deleteAccount}=require('../controllers/users')
const {auth,itsAdmin}=require('../middleware/auth')
const validateRegister = require('../middleware/validateRegister')
const validateLogin =require('../middleware/validateLogin')
const validateMongoId=require('../middleware/validId')
router.route('/login').post(validateLogin,login)
router.route('/register').post(validateRegister,register)
router.route('/allUsers').get(auth,itsAdmin,getAllUserProfile)
router.route('/deleteuser/:id').delete(validateMongoId,auth,itsAdmin,deleteUser)
router.route('/deleteAcc/:id').delete(validateMongoId,auth,deleteAccount)
module.exports=router